name: .NET Build (Compilar Todos los Proyectos)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest 

    strategy:
      matrix:
        project-path:
          - 'Bancojido'
          - 'Condicionalmayor'
          - 'ContactosEmpresax - Copy'
          - 'ContactosEmpresax'
          - 'InvestigacionPOO'
          - 'LibroDeCalificaciones'
          - 'Mayor'
          - 'Mipersona'
          - 'OpenTK/MiProyectoOpenTK'
          - 'Programacion/TipoDato'
          - 'Repeticion'
          - 'SueldoEmpleado'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore "${{ matrix.project-path }}"

    - name: Build
      run: dotnet build "${{ matrix.project-path }}" --no-restore
